### ISSUE TITLE
initWiFi is probably wrong

### ISSUE THREAD

**Issue by alonf** [Azure-Samples/iot-hub-c-thingdev-getstartedkit#23]
I think that the code should be:

status = WiFi.begin(ssid, pass);

    while (WiFi.status() != WL_CONNECTED) {
        delay(500);
        Serial.print(".");
    }

    Serial.println("Connected to wifi");

**Comment by Ilias-Tsigkogiannis** [comment]
Thanks for your comment. This has been fixed.
