### ISSUE TITLE
Remote monitoring example compile error.

### ISSUE THREAD

**Issue by santaimpersonator** [Azure-Samples/iot-hub-c-thingdev-getstartedkit#29]
So, I'm not sure why I can't get the sample code to compile or what the verbose output means.

I'm following the tutorial here for the first example **Running a Simple Remote Monitoring Solution with the SparkFun ESP8266 Thing Dev Kit (Arduino-compatible)**:
https://azure.microsoft.com/en-us/resources/samples/iot-hub-c-thingdev-getstartedkit/
I get stuck in section 1.8 where the code compiles:
https://azure.microsoft.com/en-us/resources/samples/iot-hub-c-thingdev-getstartedkit/#section1.8

*********ERROR MESSAGE***********************************************************************************

C:\Users\AppData\Local\Temp\arduino_build_41842\libraries\AzureIoTHub\sdk\agenttypesystem.c.o: In function `sscanfd':

C:\Users\Documents\Arduino\libraries\AzureIoTHub\src\sdk/agenttypesystem.c:2826: undefined reference to `strtoull'

C:\Users\AppData\Local\Temp\arduino_build_41842\libraries\AzureIoTHub\sdk\agenttypesystem.c.o: In function `sscanfllu':

C:\Users\Documents\Arduino\libraries\AzureIoTHub\src\sdk/agenttypesystem.c:2826: undefined reference to `strtoull'

C:\Users\AppData\Local\Temp\arduino_build_41842\libraries\AzureIoTHub\sdk\agenttypesystem.c.o:(.text.CreateAgentDataType_From_String+0xac): undefined reference to `strtof'

C:\Users\AppData\Local\Temp\arduino_build_41842\libraries\AzureIoTHub\sdk\agenttypesystem.c.o: In function `CreateAgentDataType_From_String':

C:\Users\Documents\Arduino\libraries\AzureIoTHub\src\sdk/agenttypesystem.c:3571: undefined reference to `strtof'

collect2.exe: error: ld returned 1 exit status

Using library AzureIoTHub at version 1.0.44 in folder: C:\Users\Documents\Arduino\libraries\AzureIoTHub 
Using library AzureIoTUtility at version 1.0.44 in folder: C:\Users\Documents\Arduino\libraries\AzureIoTUtility 
Using library AzureIoTProtocol_MQTT at version 1.0.44 in folder: C:\Users\Documents\Arduino\libraries\AzureIoTProtocol_MQTT 
Using library Adafruit_Unified_Sensor at version 1.0.2 in folder: C:\Users\Documents\Arduino\libraries\Adafruit_Unified_Sensor 
Using library DHT_sensor_library at version 1.3.0 in folder: C:\Users\Documents\Arduino\libraries\DHT_sensor_library 
Using library ESP8266WiFi at version 1.0 in folder: C:\Users\AppData\Local\Arduino15\packages\esp8266\hardware\esp8266\2.1.0\libraries\ESP8266WiFi 
exit status 1
Error compiling for board SparkFun ESP8266 Thing Dev.

**Comment by JetstreamRoySprowl** [comment]
@santaimpersonator : The missing 'strtof' is an indication that your version of the ESP8266 library is out of date. The "ESP8266 by ESP8266 community" library needs to be at least v 2.4.0
